//------------------------------------------------------------------------------
class LoremIpsum extends HTMLElement {
    //--------------------------------------------------------------------------
    constructor(id, title) {

        super();

        this.loremIpsum = [];

        this.loremIpsum.push('<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus magna quis lectus cursus, in lobortis turpis commodo. Maecenas magna dui, maximus vitae est vitae, condimentum consequat arcu. Sed at faucibus est. Nam gravida varius arcu et imperdiet. Nulla eget lectus nulla. Cras quis cursus libero. Nunc arcu augue, sollicitudin at mattis eget, imperdiet id felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>');
        this.loremIpsum.push('<p>Curabitur a lectus ex. Curabitur eget fringilla urna, at scelerisque risus. Nulla imperdiet sapien id ligula venenatis, nec vulputate diam porttitor. Nunc suscipit quis nunc id eleifend. Praesent tempus non sem ac pellentesque. Vivamus tincidunt nec sapien at aliquam. Aliquam faucibus odio in quam venenatis accumsan. Nam velit sem, imperdiet a condimentum volutpat, vehicula sit amet nulla. Sed nec rhoncus orci. Duis vulputate volutpat odio, a vestibulum diam scelerisque eu. Mauris auctor orci eget vestibulum tincidunt.</p>');
        this.loremIpsum.push('<p>Aliquam aliquet nulla non metus fermentum, sit amet dictum nunc mollis. Duis vel arcu justo. Aliquam posuere sagittis metus et posuere. Vivamus dapibus sed lectus id luctus. Donec sit amet ipsum et leo condimentum interdum nec a erat. Morbi pretium faucibus elit, ut feugiat tortor ullamcorper nec. Mauris non laoreet lacus, cursus maximus orci. In condimentum eu sem ut maximus. Fusce vehicula sodales mattis. Donec non orci ligula. Donec fringilla purus vitae finibus eleifend. Donec a enim fermentum, pulvinar est in, suscipit odio. Nulla sit amet convallis augue. Sed consequat ex at sodales tincidunt.</p>');
        this.loremIpsum.push('<p>Quisque sagittis lorem eu purus euismod faucibus. Sed nec arcu a purus dapibus tristique. Maecenas nunc felis, varius nec hendrerit ut, tempus in ex. Maecenas et venenatis orci. Aliquam pulvinar egestas fermentum. Aliquam ac eros ultrices, auctor est id, rhoncus lorem. Donec tellus tellus, vulputate non metus in, suscipit sagittis magna. Sed et varius velit, eget sodales sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse feugiat sagittis ante, et imperdiet quam accumsan sed. Aenean ut ex vitae libero imperdiet venenatis. Nulla ultrices enim neque, nec pulvinar massa ornare in. Etiam in dictum metus. Phasellus mi lacus, dapibus sed neque eu, efficitur sodales odio. Fusce non lacus vitae nibh fringilla placerat. Aliquam vel semper magna.</p>');
        this.loremIpsum.push('<p>Vivamus pellentesque viverra magna, nec posuere odio egestas eu. Integer pellentesque dolor eu mauris pulvinar, at venenatis elit sollicitudin. In pulvinar id turpis consectetur egestas. Cras felis eros, varius sed tellus convallis, tempor rutrum ligula. Morbi vitae nunc nibh. Maecenas ac varius ipsum, non sodales augue. Aenean accumsan ultricies elementum. Vestibulum ut euismod libero. Aliquam vestibulum posuere purus non porta. Ut velit mi, posuere sit amet consectetur at, mattis sed ligula. Praesent ut sollicitudin quam. Vivamus ornare dui non leo euismod pulvinar id eget quam. Donec non ex eget elit tincidunt dignissim eu id purus. Phasellus vel lectus eu nibh hendrerit molestie.</p>');
        this.loremIpsum.push('<p>Suspendisse potenti. Quisque pretium vulputate nisi vitae scelerisque. Aenean lectus nisl, mollis nec gravida ultrices, pretium congue leo. Vivamus pretium at eros a sodales. Nam lobortis sem lorem, nec aliquet elit elementum in. Vestibulum felis leo, sodales a mauris ultricies, convallis vulputate diam. Sed vitae purus in eros convallis eleifend. Pellentesque scelerisque nisl eget imperdiet congue. Aliquam erat volutpat. Fusce interdum eget ante id vulputate.</p>');
        this.loremIpsum.push('<p>Vestibulum vehicula ante a ipsum elementum suscipit. Praesent porta hendrerit est vitae efficitur. Sed id lacus sagittis, luctus nunc sit amet, tempor orci. Aliquam vel eros quis nisi viverra porta in sed ex. Suspendisse id mauris massa. Vivamus euismod, justo aliquet viverra congue, ligula velit maximus erat, ut bibendum augue dui at massa. Pellentesque ultricies lacus lorem, vel tempor odio ultrices id. Cras pulvinar nulla quis lacinia volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur aliquam ligula at gravida mollis. In semper fermentum fermentum. Sed vitae pharetra massa.</p>');
        this.loremIpsum.push('<p>Vestibulum et vulputate sapien. Donec bibendum pellentesque rhoncus. Nulla urna purus, efficitur vitae turpis at, condimentum cursus velit. Phasellus consectetur massa turpis, eu semper elit eleifend porta. Maecenas enim arcu, pharetra vitae vestibulum non, pretium et risus. Phasellus aliquam velit ut nibh placerat finibus. In sit amet tempus nibh, sit amet commodo magna. Donec interdum tempor fermentum. Mauris porta ipsum ipsum, at lobortis enim pretium sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas congue sem ut cursus dictum. Nullam ac sapien vestibulum, cursus ante nec, ullamcorper tortor. Nulla tempus elit a nulla mollis, quis consectetur metus sollicitudin. Proin facilisis, ligula vitae posuere placerat, erat nisi tristique risus, vitae hendrerit nibh ligula at leo.</p>');
        this.loremIpsum.push('<p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur ut lacinia massa. In vel nibh vitae dui iaculis viverra. Quisque sed vehicula quam. Pellentesque finibus mi neque, non lacinia dolor blandit vitae. Quisque vulputate augue tellus, a iaculis arcu viverra sit amet. Vestibulum convallis porta varius. In vitae ornare neque, quis consectetur velit. Fusce et eros ornare, tempus leo vel, aliquet ipsum. Fusce ac maximus urna, ac gravida ipsum. Maecenas ac pharetra turpis. Morbi nec felis scelerisque, consectetur velit eu, semper tellus. In eget velit ultricies, ornare felis ac, hendrerit quam. Integer diam mauris, porta at vehicula ac, sodales vel nunc. Donec posuere, ante ac maximus malesuada, odio nisi dictum justo, nec pellentesque arcu massa nec massa. Donec eu purus nulla.</p>');
        this.loremIpsum.push('<p>Cras erat eros, pulvinar id est quis, eleifend sagittis enim. Mauris convallis diam et semper aliquam. In ante diam, eleifend nec dictum pretium, hendrerit non augue. Nullam facilisis magna in nunc egestas, et porta mi tristique. Donec fermentum, risus in convallis congue, justo tortor feugiat nulla, a vulputate justo nisi ut tellus. Curabitur dapibus sit amet urna ac faucibus. Nulla laoreet odio a mollis luctus. Curabitur non urna ut dolor pharetra tincidunt. Donec placerat lectus eget dui tempus, tincidunt tincidunt tellus fringilla. Etiam vel neque nec leo efficitur gravida. Sed dignissim maximus quam vel pretium. Vestibulum ultrices ut risus at tincidunt. Morbi pellentesque ligula dui, vel viverra ex posuere faucibus. Nulla sit amet volutpat dolor. Sed gravida purus id tellus lacinia, id aliquam libero consequat. Morbi sit amet mi ut mauris sodales tempus ac vitae diam.</p>');
        this.loremIpsum.push('<p>Pellentesque eget aliquet felis. Donec in leo venenatis, vulputate lectus sed, fringilla urna. Donec tristique ex ut nibh placerat accumsan. Etiam porta, turpis a congue tristique, nibh arcu placerat est, a porta quam justo sit amet arcu. Nulla vulputate turpis a arcu tincidunt molestie. Etiam iaculis nisl in erat rhoncus, iaculis condimentum lectus posuere. Aliquam non lorem lacus. Mauris dignissim neque eu nibh sollicitudin iaculis. Nullam tincidunt erat non dui finibus, et cursus nisi varius. Nullam nec maximus magna. Nunc lobortis ac neque at faucibus.</p>');
        this.loremIpsum.push('<p>Suspendisse quis dignissim leo. Integer tristique urna a congue accumsan. Duis eu sem at turpis ornare vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque et placerat purus. Integer tempus arcu ac arcu ultricies eleifend. Curabitur tincidunt sagittis mi, in dictum tellus accumsan a. Vivamus vitae libero nisl.</p>');
        this.loremIpsum.push('<p>Pellentesque sollicitudin tempus purus, eget tempus mi finibus nec. Cras ligula purus, gravida nec fringilla ut, pretium vitae purus. Praesent quis elit non sem placerat tincidunt. Nulla in porta ex. Ut neque lectus, rhoncus non vehicula quis, blandit nec massa. Vestibulum sollicitudin vitae nulla nec aliquam. Curabitur sit amet pulvinar felis.</p>');
        this.loremIpsum.push('<p>Cras in massa tristique, sollicitudin est sed, ultrices diam. Suspendisse convallis volutpat mattis. Nullam neque odio, placerat ut dolor et, posuere malesuada lacus. Phasellus eu blandit est. Praesent non ligula non tortor euismod malesuada. Curabitur sit amet augue ex. Duis laoreet erat eu facilisis finibus. Curabitur sapien odio, placerat at massa ac, sagittis ornare metus. Integer accumsan sit amet dolor vitae ultrices. Praesent tortor erat, facilisis sed purus nec, gravida ultricies massa.</p>');
        this.loremIpsum.push('<p>In id leo leo. Fusce pharetra neque orci, lobortis euismod purus cursus ac. Praesent pulvinar id arcu sit amet pellentesque. Nunc varius enim et enim scelerisque, vel hendrerit sem laoreet. Maecenas mollis posuere purus, eget ullamcorper turpis facilisis sed. Nulla congue nisi sit amet placerat iaculis. Proin quis vehicula risus.</p>');
        this.loremIpsum.push('<p>Phasellus faucibus feugiat sapien. Maecenas fermentum, diam non dapibus dictum, arcu augue gravida nulla, nec congue felis ipsum et ipsum. Nunc pellentesque urna ipsum, eu hendrerit urna sagittis sed. Vestibulum venenatis tempor dictum. Mauris ac dui in quam sagittis semper in at dui. Ut pretium elit vitae quam placerat bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pretium nibh et erat sodales viverra. Aenean quis sem ac orci dictum cursus at vitae neque. Mauris fringilla molestie mauris, ut condimentum nisi interdum et. Nam erat nisi, cursus non nisi ut, porta ultrices neque. Integer convallis vitae ante et ornare. Nunc tincidunt hendrerit rhoncus.</p>');
        this.loremIpsum.push('<p>Vestibulum semper odio sit amet ante semper placerat. Morbi non tellus elit. Fusce interdum quis ipsum congue viverra. Suspendisse egestas justo sed efficitur ultrices. Nulla ligula est, commodo ut dui bibendum, pulvinar porttitor enim. Nulla eget lectus accumsan, interdum erat feugiat, mollis massa. Praesent mi felis, egestas consectetur tempus eu, sagittis non elit. Maecenas in neque quis tortor ultricies ultricies nec nec dolor. Integer egestas interdum venenatis. Aenean in venenatis mauris, ut mollis tellus. Nam imperdiet enim sem, eget tempus dolor tincidunt egestas. Aenean euismod, purus et convallis sollicitudin, urna arcu sodales eros, id malesuada nibh tortor non lacus.</p>');
        this.loremIpsum.push('<p>Vivamus bibendum luctus enim et ultrices. Aenean a diam nec tellus sodales dictum eget ut leo. Duis non arcu eget eros blandit fringilla sit amet vitae urna. Morbi lectus sem, aliquet sit amet finibus gravida, ornare varius elit. Quisque porttitor neque justo, et condimentum libero facilisis eget. Donec vitae nunc ac elit blandit ornare. Vestibulum quis feugiat massa. Vivamus faucibus ligula quis ante blandit, vel euismod velit accumsan.</p>');
        this.loremIpsum.push('<p>Donec ullamcorper congue augue, non egestas tortor pharetra blandit. Proin a vulputate eros. Mauris interdum orci augue, a tincidunt nulla vehicula sit amet. Sed rutrum laoreet eleifend. Nullam pellentesque vel mauris nec gravida. Nulla iaculis vel nunc a ornare. Nunc ac mauris non risus maximus tincidunt. Donec tempor sapien sodales dui sagittis, et scelerisque turpis accumsan. Phasellus at bibendum lectus, nec efficitur enim. Cras tristique tempus tortor, ut tristique mi convallis ut. Proin imperdiet ut nisi ac faucibus.</p>');
        this.loremIpsum.push('<p>Aliquam eget massa nisl. Duis lorem ipsum, congue nec lobortis in, aliquam at lectus. Sed semper tincidunt libero, ac tristique nulla molestie ac. Pellentesque ut enim vestibulum, rutrum eros id, ultricies quam. Integer nec diam sed lacus ultricies fermentum. Quisque in ultricies ipsum. Pellentesque pellentesque turpis lectus, vel semper magna euismod at. Ut suscipit dictum nulla, a interdum turpis accumsan quis. Aenean non eros semper, bibendum est id, mollis magna. Mauris mi sapien, lobortis ut condimentum at, tincidunt quis elit. Nunc cursus, nisl vel auctor imperdiet, est massa placerat augue, nec tristique ligula sapien quis leo. Vivamus eu vehicula lacus, sit amet aliquet lectus. Sed efficitur, libero quis iaculis lacinia, lectus augue volutpat nibh, molestie sagittis felis velit id leo. Nunc non sem iaculis, elementum augue eget, tristique mauris.</p>');
        this.loremIpsum.push('<p>Proin fringilla velit eros, non tempor tortor rutrum in. Aliquam vestibulum, risus eget consequat cursus, mi tellus suscipit nibh, a malesuada dui eros ut eros. Cras sed magna ac magna dictum tincidunt. Donec sit amet commodo velit. Proin vitae magna hendrerit, lacinia urna at, accumsan leo. Praesent facilisis libero purus, quis vestibulum lorem egestas eu. Cras convallis, libero a accumsan tristique, nulla mauris tristique nibh, non tempus nisi odio eu nisl. Curabitur tempus sit amet lorem ac commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin mattis enim a sem tincidunt, sed mollis ex euismod. Vivamus venenatis sapien mauris, nec lobortis libero varius in. Cras vitae libero in diam ullamcorper auctor. Vivamus eu ipsum vitae nibh gravida semper et sit amet turpis. Cras sit amet ante ac purus auctor rhoncus. Suspendisse ullamcorper elit id sem tristique malesuada. Phasellus arcu massa, dapibus ut rhoncus vitae, accumsan quis nulla.</p>');
        this.loremIpsum.push('<p>Sed pellentesque malesuada tellus, eu ultricies enim pulvinar sit amet. Nunc ante dui, pellentesque quis egestas nec, suscipit vitae sem. Morbi sollicitudin, ante sed lobortis commodo, dolor est molestie orci, quis varius dui magna quis lacus. Nullam ultrices facilisis sapien et lobortis. In nisl lectus, elementum at enim non, volutpat iaculis metus. Nulla volutpat arcu ut mi malesuada, accumsan consequat eros convallis. Sed facilisis suscipit massa, nec bibendum ante facilisis sed. Aenean quis velit sit amet est sodales posuere. Pellentesque dapibus, ex a rhoncus aliquet, arcu leo finibus nulla, et pharetra orci augue sit amet dui. Curabitur commodo dignissim eros eget elementum. Sed lobortis urna ornare, consectetur lectus ut, mollis felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut sapien pretium, tincidunt justo non, pellentesque sem. Cras iaculis quam non lectus fringilla laoreet. Proin lacinia quis tortor eu tincidunt. Nam fermentum facilisis nulla at placerat.</p>');
        this.loremIpsum.push('<p>Curabitur vel nisi nisl. Praesent ut nunc porta, efficitur eros eget, rutrum tortor. Sed metus mi, ultricies in nisi sed, cursus porttitor tellus. Etiam in ex tristique, aliquam mauris vitae, volutpat purus. Morbi leo urna, pellentesque et laoreet ac, vehicula sed orci. Aliquam posuere viverra erat, eget dictum tortor tincidunt a. Praesent eleifend nunc eu ullamcorper interdum. Vestibulum convallis dignissim tellus, scelerisque semper urna accumsan eu. Suspendisse maximus augue maximus, viverra risus vitae, interdum sem. Proin sed mauris bibendum, bibendum enim sit amet, molestie nisi. Nulla facilisi. Suspendisse vitae purus turpis. Proin accumsan, nulla et fermentum commodo, tellus lorem venenatis enim, sit amet molestie quam sem vitae diam. Maecenas vestibulum vel quam id tempus. Quisque molestie vulputate risus, sodales molestie quam elementum eu. Suspendisse tempor gravida tincidunt.</p>');
        this.loremIpsum.push('<p>Sed placerat congue sem, ac placerat dolor bibendum rutrum. Integer eu efficitur dolor. Integer non sagittis dolor. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin ac molestie ligula, vel elementum tortor. Nam hendrerit consequat nunc, sit amet elementum leo congue a. Fusce tempor, erat sed sollicitudin semper, quam odio placerat leo, id feugiat nisi turpis ut enim. In gravida, massa molestie placerat bibendum, velit mauris consequat ipsum, et malesuada orci mi ac sapien. Praesent ac velit efficitur, pharetra ligula et, tempor tortor.</p>');
        this.loremIpsum.push('<p>In erat lorem, iaculis ac ligula eu, rutrum finibus turpis. Suspendisse augue turpis, pharetra a diam vel, congue suscipit turpis. Vestibulum nulla enim, pretium ac rhoncus a, rutrum vitae felis. Etiam vitae pharetra purus. Phasellus ut erat luctus, ultrices elit non, bibendum leo. Sed cursus, justo sed faucibus efficitur, justo nulla pellentesque velit, at scelerisque lectus leo vel massa. Duis commodo eleifend mauris vitae congue. Phasellus luctus lacinia elit, et iaculis felis tempor non. Aliquam semper lacus iaculis, rutrum ex vitae, interdum massa. In leo lectus, pulvinar in velit porttitor, ullamcorper consequat felis. Aliquam efficitur orci nec nisi dignissim, venenatis faucibus magna sodales. Donec ac erat ac augue rhoncus semper. Etiam sed mi ut turpis ornare tempus a sit amet neque. Aenean tortor libero, lobortis a vestibulum elementum, facilisis vitae tortor.</p>');

    }
    //--------------------------------------------------------------------------
    connectedCallback() {
        
        let limit = -1;

        if (this.hasAttribute('limit')) {
            limit = this.getAttribute('limit');
        }

        if (limit < 0 || limit >= this.loremIpsum.length) {
            limit = this.loremIpsum.length - 1;
        }


        let html = ``;

        for (var i = 0; i <= limit; i++) {
            html += this.loremIpsum[i];
        }

        this.innerHTML = html;

    }
    //--------------------------------------------------------------------------
}
//------------------------------------------------------------------------------
customElements.define('lorem-ipsum', LoremIpsum);
//------------------------------------------------------------------------------